# Generated by Django 6.0.4 on 2026-04-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('main_category', models.CharField(choices=[('work', 'Work Experience'), ('project', 'Projects'), ('education', 'Education'), ('skills', 'Skills and Qualifications'), ('volunteer', 'Volunteer Experience')], max_length=20)),
                ('sub_category', models.CharField(max_length=100)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
